from __future__ import annotations

from dataclasses import dataclass
import json
import os
from pathlib import Path
import re
import xml.etree.ElementTree as ET


class KeilProjectError(ValueError):
    """Raised when a Keil project cannot be converted for clang tooling."""


@dataclass(frozen=True)
class KeilProjectInfo:
    project_file: Path
    target_name: str
    device: str
    toolset: str
    source_files: tuple[Path, ...]
    include_directories: tuple[Path, ...]
    defines: tuple[str, ...]
    compile_commands: Path
    compiler: str = ""
    device_defines: tuple[str, ...] = ()
    toolchain_include: Path | None = None
    warnings: tuple[str, ...] = ()


# armcc keywords that clang does not know. They are mapped onto the GNU spelling clang
# understands so headers written for ARM Compiler 5 still parse. ``__inline`` and
# ``__asm`` are native clang keywords and need no mapping; ``__declspec`` is enabled
# through ``-fdeclspec`` instead of a macro so its argument list keeps working.
ARMCC_KEYWORD_DEFINES: tuple[str, ...] = (
    "__packed=__attribute__((packed))",
    "__weak=__attribute__((weak))",
    "__align(n)=__attribute__((aligned(n)))",
    "__forceinline=__attribute__((always_inline)) inline",
    "__pure=__attribute__((const))",
    "__irq=",
    "__softfp=",
    "__svc(n)=",
    "__smc(n)=",
    "__value_in_regs=",
    "__int64=long long",
)

# ARM Compiler 5 provides these without any header; clang only sees them when we
# declare them. ``static inline`` declarations stay compatible with the CMSIS GCC
# definitions (``__STATIC_INLINE void __disable_irq(void) {...}``) that some units include.
ARMCC_INTRINSICS_HEADER = """\
/* Generated by archcheck. ARM Compiler 5 intrinsics that armcc provides without a header. */
#ifndef ARCHCHECK_ARMCC_INTRINSICS_H
#define ARCHCHECK_ARMCC_INTRINSICS_H
static inline void __enable_irq(void);
static inline void __disable_irq(void);
static inline void __enable_fiq(void);
static inline void __disable_fiq(void);
void __nop(void);
void __wfi(void);
void __wfe(void);
void __sev(void);
void __yield(void);
void __isb(unsigned int);
void __dsb(unsigned int);
void __dmb(unsigned int);
void __breakpoint(int);
void __schedule_barrier(void);
void __force_stores(void);
void __memory_changed(void);
unsigned int __clz(unsigned int);
unsigned int __rev(unsigned int);
unsigned int __rbit(unsigned int);
unsigned int __ror(unsigned int, unsigned int);
int __ssat(int, unsigned int);
unsigned int __usat(unsigned int, unsigned int);
int __qadd(int, int);
int __qsub(int, int);
int __qdbl(int);
unsigned int __current_sp(void);
unsigned int __current_pc(void);
unsigned int __return_address(void);
unsigned int __ldrex(volatile void *);
int __strex(unsigned int, volatile void *);
void __clrex(void);
int __semihost(int, const void *);
/* __sqrt / __sqrtf / __fabs / __fabsf need <math.h> under armcc too; the ARM math.h declares them. */
#endif
"""

TOOLCHAIN_INCLUDE_ENV = "ARCHCHECK_KEIL_TOOLCHAIN_INCLUDE"
KEIL_ROOT_ENV = "ARCHCHECK_KEIL_ROOT"


def find_keil_projects(project: Path) -> tuple[Path, ...]:
    ignored = {".git", "Objects", "Listings", "build", "output"}
    matches = []
    for path in project.rglob("*.uvprojx"):
        if not any(part in ignored for part in path.parts):
            matches.append(path.resolve())
    return tuple(sorted(matches, key=lambda item: str(item).casefold()))


def list_keil_targets(project_file: Path) -> tuple[str, ...]:
    project_file = project_file.expanduser().resolve()
    if not project_file.is_file():
        raise KeilProjectError(f"Keil 工程不存在：{project_file}")
    try:
        root = ET.parse(project_file).getroot()
    except ET.ParseError as exc:
        raise KeilProjectError(f"Keil 工程 XML 无效：{exc}") from exc
    return tuple(
        name
        for target in root.findall("./Targets/Target")
        if (name := _text(target, "TargetName"))
    )


def write_keil_compilation_database(
    project: Path,
    project_file: Path,
    destination: Path,
    target_name: str | None = None,
    toolchain_include: Path | None = None,
    extra_defines: tuple[str, ...] = (),
    keil_roots: tuple[Path, ...] | None = None,
    pack_roots: tuple[Path, ...] | None = None,
) -> KeilProjectInfo:
    """Translate one Keil target into a clang compilation database.

    ``toolchain_include`` overrides the compiler system-header directory (falls back to
    ``ARCHCHECK_KEIL_TOOLCHAIN_INCLUDE`` and then to auto-detection of the Keil install).
    ``keil_roots`` / ``pack_roots`` replace the auto-detected Keil ``ARM`` directories and
    CMSIS-Pack roots; tests use them to stay independent of the machine.
    """
    project = project.expanduser().resolve()
    project_file = project_file.expanduser().resolve()
    if not project_file.is_file():
        raise KeilProjectError(f"Keil 工程不存在：{project_file}")

    try:
        root = ET.parse(project_file).getroot()
    except ET.ParseError as exc:
        raise KeilProjectError(f"Keil 工程 XML 无效：{exc}") from exc

    targets = root.findall("./Targets/Target")
    if not targets:
        raise KeilProjectError("Keil 工程没有 Target")
    target = _select_target(targets, target_name)
    selected_name = _text(target, "TargetName") or "target"
    common = target.find("./TargetOption/TargetCommonOption")
    arm = target.find("./TargetOption/TargetArmAds")
    device = _text(common, "Device")
    cpu = _text(common, "Cpu")
    pack_id = _text(common, "PackID")
    toolset = _text(target, "ToolsetName")
    uses_armclang = _text(target, "uAC6") == "1"
    compiler = _describe_compiler(uses_armclang, _text(target, "pCCUsed"))
    controls = arm.find("./Cads/VariousControls") if arm is not None else None
    include_directories = _resolve_paths(
        project_file.parent,
        _split_semicolon(_text(controls, "IncludePath"))
        + _split_semicolon(_text(common, "IncludePath")),
    )
    defines = tuple(
        item for item in re.split(r"[,\s]+", _text(controls, "Define")) if item
    ) + tuple(item for item in extra_defines if item)

    source_files = []
    for file_node in target.findall("./Groups/Group/Files/File"):
        file_path = _text(file_node, "FilePath")
        if not file_path:
            continue
        resolved = (project_file.parent / Path(file_path.replace("\\", "/"))).resolve()
        if resolved.suffix.lower() in {".c", ".cc", ".cpp", ".cxx", ".s", ".asm"}:
            source_files.append(resolved)
    source_files = sorted(set(source_files), key=lambda item: str(item).casefold())
    if not source_files:
        raise KeilProjectError(f"Keil Target {selected_name} 没有源文件")

    warnings: list[str] = []
    arm_roots = tuple(keil_roots) if keil_roots is not None else _detect_keil_arm_roots()
    resolved_pack_roots = (
        tuple(pack_roots) if pack_roots is not None else _detect_pack_roots(arm_roots)
    )
    device_defines, pack_includes = _device_pack_settings(
        resolved_pack_roots, pack_id, device, defines, warnings
    )
    system_include = _resolve_toolchain_include(toolchain_include, arm_roots, warnings)

    destination.mkdir(parents=True, exist_ok=True)
    intrinsics_header: Path | None = None
    if not uses_armclang:
        intrinsics_header = destination / "archcheck_armcc_intrinsics.h"
        intrinsics_header.write_text(ARMCC_INTRINSICS_HEADER, encoding="utf-8")

    target_cpu = _clang_cpu(cpu, device)
    entries = []
    for source in source_files:
        language = "c++" if source.suffix.lower() in {".cc", ".cpp", ".cxx"} else "c"
        arguments = [
            "clang",
            "--target=arm-none-eabi",
            f"-mcpu={target_cpu}",
            "-mthumb",
            "-x",
            language,
            "-std=gnu++17" if language == "c++" else "-std=gnu11",
            "-Wno-unknown-attributes",
            # The intrinsics shim declares static inline functions that only CMSIS defines.
            "-Wno-undefined-inline",
            "-Wno-undefined-internal",
            "-fdeclspec",
        ]
        arguments.extend(f"-D{item}" for item in defines)
        arguments.extend(f"-D{item}" for item in device_defines)
        arguments.extend(f"-D{item}" for item in ARMCC_KEYWORD_DEFINES)
        arguments.extend(f"-I{path}" for path in include_directories if path.is_dir())
        arguments.extend(f"-I{path}" for path in pack_includes)
        if system_include is not None:
            arguments.extend(("-isystem", str(system_include)))
        if intrinsics_header is not None:
            arguments.extend(("-include", str(intrinsics_header)))
        arguments.extend(("-c", str(source)))
        entries.append(
            {
                "directory": str(project),
                "file": str(source),
                "arguments": arguments,
            }
        )

    output = destination / "compile_commands.json"
    output.write_text(
        json.dumps(entries, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    return KeilProjectInfo(
        project_file=project_file,
        target_name=selected_name,
        device=device,
        toolset=toolset,
        source_files=tuple(source_files),
        include_directories=include_directories,
        defines=defines,
        compile_commands=output.resolve(),
        compiler=compiler,
        device_defines=device_defines,
        toolchain_include=system_include,
        warnings=tuple(warnings),
    )


def _select_target(targets: list[ET.Element], target_name: str | None) -> ET.Element:
    if target_name is None:
        if len(targets) == 1:
            return targets[0]
        names = ", ".join(_text(item, "TargetName") for item in targets)
        raise KeilProjectError(f"Keil 工程包含多个 Target，请指定一个：{names}")
    for target in targets:
        if _text(target, "TargetName") == target_name:
            return target
    names = ", ".join(_text(item, "TargetName") for item in targets)
    raise KeilProjectError(f"Keil Target 不存在：{target_name}；可选：{names}")


def _text(parent: ET.Element | None, path: str) -> str:
    if parent is None:
        return ""
    node = parent.find(path)
    return (node.text or "").strip() if node is not None else ""


def _split_semicolon(value: str) -> tuple[str, ...]:
    return tuple(item.strip() for item in value.split(";") if item.strip())


def _resolve_paths(base: Path, values: tuple[str, ...]) -> tuple[Path, ...]:
    return tuple(
        sorted(
            {(base / Path(value.replace("\\", "/"))).resolve() for value in values},
            key=lambda item: str(item).casefold(),
        )
    )


def _describe_compiler(uses_armclang: bool, cc_used: str) -> str:
    # pCCUsed looks like ``5060960::V5.06 update 7 (build 960)::.\ARMCC``.
    parts = [part for part in cc_used.split("::") if part]
    version = parts[1] if len(parts) >= 2 else ""
    name = "ARMCLANG" if uses_armclang else "ARMCC"
    return f"{name} {version}".strip()


def _clang_cpu(cpu: str, device: str) -> str:
    match = re.search(r'CPUTYPE\("([^"]+)"\)', cpu, re.IGNORECASE)
    value = match.group(1) if match else device
    normalized = value.lower().replace(" ", "")
    mappings = {
        "cortex-m0": "cortex-m0",
        "cortex-m0+": "cortex-m0plus",
        "cortex-m3": "cortex-m3",
        "cortex-m4": "cortex-m4",
        "cortex-m7": "cortex-m7",
        "cortex-m23": "cortex-m23",
        "cortex-m33": "cortex-m33",
    }
    for marker, clang_name in mappings.items():
        if marker in normalized:
            return clang_name
    return "cortex-m4"


# --- Keil installation discovery -------------------------------------------------


def _detect_keil_arm_roots() -> tuple[Path, ...]:
    """Directories like ``C:\\Keil_v5\\ARM`` that hold ``ARMCC`` / ``ARMCLANG``."""
    candidates: list[Path] = []
    env_root = os.environ.get(KEIL_ROOT_ENV)
    if env_root:
        root = Path(env_root).expanduser()
        candidates.extend((root / "ARM", root))
    candidates.extend(_registry_keil_roots())
    for drive in ("C", "D", "E", "F"):
        candidates.append(Path(f"{drive}:/Keil_v5/ARM"))
        candidates.append(Path(f"{drive}:/Keil/ARM"))
    roots: list[Path] = []
    for candidate in candidates:
        if not candidate.is_dir():
            continue
        if not ((candidate / "ARMCC").is_dir() or (candidate / "ARMCLANG").is_dir()):
            continue
        resolved = candidate.resolve()
        if resolved not in roots:
            roots.append(resolved)
    return tuple(roots)


def _registry_keil_roots() -> list[Path]:
    try:
        import winreg  # type: ignore[import-not-found]
    except ImportError:
        return []
    roots: list[Path] = []
    keys = (
        (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\WOW6432Node\Keil\Products\MDK"),
        (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Keil\Products\MDK"),
        (winreg.HKEY_CURRENT_USER, r"SOFTWARE\Keil\Products\MDK"),
    )
    for hive, key_path in keys:
        try:
            with winreg.OpenKey(hive, key_path) as key:
                value, _ = winreg.QueryValueEx(key, "Path")
        except OSError:
            continue
        if isinstance(value, str) and value:
            roots.append(Path(value))
    return roots


def _detect_pack_roots(arm_roots: tuple[Path, ...]) -> tuple[Path, ...]:
    """CMSIS-Pack roots: TOOLS.INI ``RTEPATH``, ``<ARM>\\PACK`` and the Arm default."""
    roots: list[Path] = []
    for arm_root in arm_roots:
        tools_ini = arm_root.parent / "TOOLS.INI"
        if tools_ini.is_file():
            try:
                text = tools_ini.read_text(encoding="utf-8", errors="ignore")
            except OSError:
                text = ""
            for match in re.finditer(r'^\s*RTEPATH\s*=\s*"?([^"\r\n]+)"?', text, re.MULTILINE):
                roots.append(Path(match.group(1).strip()))
        roots.append(arm_root / "PACK")
    local_app_data = os.environ.get("LOCALAPPDATA")
    if local_app_data:
        roots.append(Path(local_app_data) / "Arm" / "Packs")
    unique: list[Path] = []
    for root in roots:
        if root.is_dir():
            resolved = root.resolve()
            if resolved not in unique:
                unique.append(resolved)
    return tuple(unique)


def _resolve_toolchain_include(
    explicit: Path | None,
    arm_roots: tuple[Path, ...],
    warnings: list[str],
) -> Path | None:
    """Pick the compiler system-header directory to pass as ``-isystem``.

    The ARMCLANG headers are written for a clang-based compiler and parse cleanly, so they
    are preferred even for ARM Compiler 5 targets; the ARMCC headers work as a fallback
    once ``__declspec`` (``-fdeclspec``) and ``__value_in_regs`` (defined empty) are
    tolerated. Both ship the same ARM C library API, so the choice does not change which
    identifiers resolve.
    """
    if explicit is None:
        env_value = os.environ.get(TOOLCHAIN_INCLUDE_ENV)
        if env_value:
            explicit = Path(env_value)
    if explicit is not None:
        explicit = explicit.expanduser()
        if explicit.is_dir():
            return explicit.resolve()
        warnings.append(f"配置的 Keil 编译器头文件目录不存在，已忽略：{explicit}")

    for name in ("ARMCLANG", "ARMCC"):
        for arm_root in arm_roots:
            candidate = arm_root / name / "include"
            if candidate.is_dir():
                if name == "ARMCC":
                    warnings.append(
                        "未找到 ARMCLANG 头文件目录，改用 ARMCC 头文件；"
                        f"armcc 私有语法可能产生少量 clang 诊断：{candidate}"
                    )
                return candidate.resolve()
    warnings.append(
        "未找到 Keil ARM 编译器头文件目录（ARM\\ARMCLANG\\include 或 ARM\\ARMCC\\include），"
        "string.h/stdio.h 等标准库头将无法解析，只剩 clang 内建头；"
        f"可通过 --keil-toolchain-include 或环境变量 {TOOLCHAIN_INCLUDE_ENV} 指定。"
    )
    return None


# --- CMSIS-Pack device settings --------------------------------------------------


def _device_pack_settings(
    pack_roots: tuple[Path, ...],
    pack_id: str,
    device: str,
    defines: tuple[str, ...],
    warnings: list[str],
) -> tuple[tuple[str, ...], tuple[Path, ...]]:
    """Device macros (and header directories) that uVision injects from the DFP.

    ``.uvprojx`` only stores the user's ``<Define>``; the device selector macro such as
    ``GD32F30X_XD`` comes from the pack's ``<compile define="...">`` for the device.
    """
    if not device:
        return (), ()
    pdsc = _find_pdsc(pack_roots, pack_id)
    if pdsc is None:
        location = "、".join(str(root) for root in pack_roots) or "（未发现 Pack 目录）"
        warnings.append(
            f"未找到器件 {device} 的 CMSIS Pack {pack_id or '?'}（搜索：{location}），"
            "器件宏无法自动补齐；如芯片头文件报“请选择器件”，请用 --keil-define 补充。"
        )
        return (), ()
    try:
        root = ET.parse(pdsc).getroot()
    except (ET.ParseError, OSError) as exc:
        warnings.append(f"CMSIS Pack 描述文件无法解析：{pdsc}：{exc}")
        return (), ()

    parents = {child: parent for parent in root.iter() for child in parent}
    node = _find_device_node(root, device)
    if node is None:
        warnings.append(f"CMSIS Pack {pdsc.name} 中没有器件 {device}，器件宏未补齐。")
        return (), ()

    chain: list[ET.Element] = []
    current: ET.Element | None = node
    while current is not None:
        chain.append(current)
        current = parents.get(current)
    existing_names = {item.split("=", 1)[0] for item in defines}
    device_defines: list[str] = []
    headers: list[Path] = []
    for element in reversed(chain):
        for compile_node in element.findall("compile"):
            define = (compile_node.get("define") or "").strip()
            if define and define not in existing_names and define not in device_defines:
                device_defines.append(define)
            header = (compile_node.get("header") or "").strip()
            if header:
                header_dir = (pdsc.parent / header.replace("\\", "/")).parent
                if header_dir.is_dir() and header_dir.resolve() not in headers:
                    headers.append(header_dir.resolve())
    return tuple(device_defines), tuple(headers)


def _find_pdsc(pack_roots: tuple[Path, ...], pack_id: str) -> Path | None:
    parts = pack_id.split(".")
    if len(parts) < 2:
        return None
    vendor, name = parts[0], parts[1]
    version = ".".join(parts[2:])
    pdsc_name = f"{vendor}.{name}.pdsc"
    for root in pack_roots:
        pack_dir = root / vendor / name
        if not pack_dir.is_dir():
            continue
        exact = pack_dir / version / pdsc_name
        if version and exact.is_file():
            return exact
        versions = sorted(
            (child for child in pack_dir.iterdir() if (child / pdsc_name).is_file()),
            key=lambda item: _version_key(item.name),
            reverse=True,
        )
        if versions:
            return versions[0] / pdsc_name
    return None


def _version_key(value: str) -> tuple[int, ...]:
    return tuple(int(part) if part.isdigit() else 0 for part in re.split(r"[.\-]", value))


def _find_device_node(root: ET.Element, device: str) -> ET.Element | None:
    wanted = device.casefold()
    for tag, attribute in (("device", "Dname"), ("variant", "Dvariant")):
        for node in root.iter(tag):
            if (node.get(attribute) or "").casefold() == wanted:
                return node
    return None
